name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "./resume-master/src"
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
